# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/254f5b66-69ea-4552-a9de-37cb1c5e09c6";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=zstd:3" "space_cache=v2" "ssd" "discard=async" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/254f5b66-69ea-4552-a9de-37cb1c5e09c6";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=zstd:3" "space_cache=v2" "ssd" "discard=async" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/254f5b66-69ea-4552-a9de-37cb1c5e09c6";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=zstd:3" "space_cache=v2" "ssd" "discard=async" "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/660B-F086";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-label/Windows";
      fsType = "ntfs-3g";
      options = [ "rw" "allow_other" "uid=1000" "gid=100" "nofail" "exec" "x-gvfs-show" "user" "umask=000" "0" "0"];
    };
  fileSystems."/mnt/xraydisk" =
    { device = "/dev/disk/by-label/XrayDisk";
      fsType = "btrfs";
      options = [ "rw" "nofail" "noatime" "compress=zstd:3" "space_cache=v2" "x-gvfs-show" ];
    };
  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-label/HDD";
      fsType = "btrfs";
      options = [ "rw" "nofail" "noatime" "compress=zstd:3" "ssd" "x-gvfs-show" "discard=async" "space_cache=v2"];
    };


  zramSwap.enable = true;
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
