[config]
version_check = false

[templates.swaync]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"
[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.neovim]
input_path = '~/.config/matugen/templates/nvim.lua'
output_path = '~/.config/nvim/matugen.lua'

[templates.helix]
input_path = '~/.config/matugen/templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.mangowc]
input_path = '~/.config/matugen/templates/mangowc.conf'
output_path = '~/.config/mango/colors.conf'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/kitty-colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.chicago]
input_path = '~/.config/matugen/templates/chicago.css'
output_path = '~/.local/share/themes/chicagoMatugen/gtk-3.24/gtk.css'

[templates.papirus]
input_path = "~/.config/matugen/templates/papirus-recolor.sh"
output_path = "~/.config/matugen/scripts/papirus-recolor-generated.sh"
post_hook = "chmod +x ~/.config/matugen/scripts/papirus-recolor-generated.sh && ~/.config/matugen/scripts/papirus-recolor-generated.sh"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.discordMidnight]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/Equicord/themes/midnight.css'

[templates.discordMaterial]
input_path = '~/.config/matugen/templates/Material-Discord.css'
output_path = '~/.config/Equicord/themes/material.css'

[templates.discordSystem24]
input_path = '~/.config/matugen/templates/system24-discord.css'
output_path = '~/.config/Equicord/themes/system24-discord.css'

[templates.fish]
input_path = '~/.config/matugen/templates/fish-colors.theme'
output_path = '~/.config/fish/themes/Matugen.theme'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.config/quickshell/Appearance/colors.json'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen.json'
