rootcolor=0x15130fff

bordercolor=0x15130fff

focuscolor=0xfff7e1ff

maximizescreencolor=0xd0c6a7ff

urgentcolor=0xffb4abff

scratchpadcolor=0xf8f6ffff

globalcolor=0x4f4931ff

overlaycolor=0xd4d8ffff
