rootcolor=0x18120bff

bordercolor=0x18120bff

focuscolor=0xffd7a0ff

maximizescreencolor=0xe7c08aff

urgentcolor=0xffb4abff

scratchpadcolor=0xb1e5ffff

globalcolor=0x5f4419ff

overlaycolor=0x53cfffff
