rootcolor=0x121318ff

bordercolor=0x121318ff

focuscolor=0xb7c4ffff

maximizescreencolor=0xbfc5e7ff

urgentcolor=0xffb4abff

scratchpadcolor=0xf7bc67ff

globalcolor=0x414864ff

overlaycolor=0x7e5300ff
