# layout support:

# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:scroller,no_hide:1
tagrule=id:2,layout_name:scroller,no_hide:1
tagrule=id:3,layout_name:scroller,no_hide:1
tagrule=id:4,layout_name:scroller,no_hide:1
tagrule=id:5,layout_name:scroller,no_hide:1
tagrule=id:6,layout_name:scroller,no_hide:1
tagrule=id:7,layout_name:scroller,no_hide:0
tagrule=id:8,layout_name:scroller,no_hide:0
tagrule=id:9,layout_name:scroller,no_hide:0


windowrule=tags:1,appid:helium
windowrule=tags:1,appid:firefox,isopensilent:1,istagsilent:1
windowrule=tags:2,appid:heroic,isopensilent:1,istagsilent:1
windowrule=tags:2,appid:hydra,isopensilent:1,istagsilent:1
windowrule=tags:2,appid:twintaillauncher,isopensilent:1,istagsilent:1
windowrule=tags:2,appid:steam,isopensilent:1,istagsilent:1
windowrule=tags:3,appid:vesktop,isopensilent:1
windowrule=tags:3,appid:discord,isopensilent:1,istagsilent:1
windowrule=tags:4,appid:foot
windowrule=tags:4,title:Genshin Impact
windowrule=tags:4,title:Zenless Zone Zero
windowrule=tags:4,title:Umamusume
windowrule=tags:4,title:Wuthering Waves
windowrule=allow_csd:1,appid:twintaillauncher
windowrule=allow_csd:0,appid:firefox
windowrule=allow_csd:1,appid:foot

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

windowrule=force_tearing:1,title:ZenlessZoneZero
windowrule=isfloating:1,width:650,height:450,appid:pavucontrol-qt
windowrule=isfloating:1,width:450,height:650,appid:clipse-gui
windowrule=isfloating:1,width:450,height:650,appid:nwg-clipman
windowrule=isfloating:1,width:450,height:650,title:clipse
windowrule=appid:com.github.hluk.copyq,isfloating:1,width:450,height:650
windowrule=force_tearing:1,title:Wuthering Waves
windowrule=isfloating:1,appid:waypaper
windowrule=isfloating:1,width:850,height:550,appid:ark
windowrule=isfloating:1,width:850,height:650,appid:org.freedesktop.impl.portal.desktop.kde
windowrule=isfloating:1,width:850,height:650,appid:xdg-desktop-portal-gtk

windowrule=isfloating:1,width:700,height:500,title:Add Non-Steam Game
windowrule=isfloating:1,width:700,height:700,title:Steam Settings
windowrule=isfloating:1,width:300,height:700,title:Friends List
windowrule=isfloating:1,width:350,height:650,title:Calculator
