exec-once = qs
exec-once = mako
exec-once = gamepad
exec-once = awww-daemon
exec-once = copyq
exec-once = nm-applet
exec-once = wlsunset -g 0.8 -t 6000 -T 6500
exec-once = firefox
exec-once = discord
exec-once = steam
exec-once = app.twintaillauncher.ttl
exec-once = heroic
