[[manager.prepend_keymap]]
on   = "i"
run  = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

[[manager.prepend_keymap]]
on   = "d"
run  = "plugin sudo -- remove"
desc = "sudo trash"

[[manager.prepend_keymap]]
on   = "D"
run  = "plugin sudo -- remove --permanently"
desc = "sudo delete"
