# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0d045490-772c-4498-bdec-e3d7825865ca";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0d045490-772c-4498-bdec-e3d7825865ca";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0d045490-772c-4498-bdec-e3d7825865ca";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2715-3789";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "noatime" ];
    };
  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-label/Windows";
      fsType = "ntfs-3g";
      options = [ "rw" "allow_other" "uid=1000" "gid=100" "nofail" "exec" "user" "umask=000" "0" "0"];
    };
  fileSystems."/mnt/ntfs" =
    { device = "/dev/disk/by-label/XrayDisk";
      fsType = "ntfs-3g";
      options = [ "rw" "allow_other" "uid=1000" "gid=100" "nofail" "exec" "user" "umask=000" "0" "0"];
    };
  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
